### ISSUE TITLE
Todo for Registratior

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/UnfoldSim.jl#3]
- [x] Readme
- [x] Check dependencies
- [x] Add Compat entries
- [x] Author => Luis Lips, Benedikt Ehinger, Judith Schepers,
- [x] Setup Continuous Integration (maybe redoing the package is easier as we can use PkgTemplate.jl?
- [x] We need unittests
- [x] We need documentation

**Comment by behinger** [comment]
starting to look good!
